### PR TITLE
Use orange strip for selected sidebar rows

### PR DESCRIPTION
**Pull request by godlyranchdressing**
To help resolve issue #289

### CODE REVIEW

**Comment by Feichtmeier** [comment]
The implementation looks good to me!
I'd say let's try this. @madsrh ?
screenshot-20180417211441-876x597

**Comment by NusiNusi** [comment]
Shouldn't the text be bold?

**Comment by NusiNusi** [comment]
okay, already merched... too late. @godlyranchdressing necessary to open an issue for the bold text + black symbol? Or will you add it next time automatically?

**Comment by godlyranchdressing** [comment]
@NusiNusi, are you not using the Ubuntu font?

**Comment by madsrh** [comment]
@NusiNusi Without haven't see it, I would say the bold font is too much. IMO we should tweak the colors and not the font weight. Anyway, we can easily experiment with that later 😃

**Comment by NusiNusi** [comment]
We already discussed this:
https://user-images.githubusercontent.com/9556384/38165696-6829f764-3552-11e8-9c98-5e9c4c53f35d.gif
This way it is the perfect equivalent to selected item in stackswitcher. The bold black text and black symbol really should be added.

**Comment by godlyranchdressing** [comment]
@NusiNusi it looks like that for me. I just tested some other fonts. I didn't think through my use of `font-weight: 500` instead of `font-weight: bold`. I was sticking to that because the bold Ubuntu font is super wide, but it looks like if another font family is used without that weight then the font will look the same.

**Comment by madsrh** [comment]
> This way it is the perfect equivalent to selected item in stackswitcher. The bold black text and black symbol really should be added.

@NusiNusi No, the bold font is only used in Nautilus because it is hardcoded. The stackswitcher (like in Software center) **isn't** bold.

We can try the bold font, but I cannot find a single other theme that has bold in the sidebar and again, off the top of my head, I would say it would be screaming for attention - we might as well make it orange 🤣

**Comment by NusiNusi** [comment]
Ah sorry! I just meant it should be as "fat" as the text in stackswitcher or just like the mockup @nana-4 made. It seems i am using the wrong vocabulary :(

**Comment by Feichtmeier** [comment]
I have to admit, that I miss the orange box too allready :| But let's see.
I've just seen the version of the theme some which is some weeks old on my fathers pc and I also miss the orange close button :| Anyone else has this very subjective, sensitive faery feelings? =D

**Comment by madsrh** [comment]
@Feichtmeier Not sure if we're getting off topic here, but IMO the close button ok when the orange block (don't know what to call it) is in the sidebar. So, I share your concerns, but at least we have until october to revert the changes 😆

**Comment by madsrh** [comment]
Is it too early to create a _"revert changes for sidebar"_ issue 🤣 

Jokes aside! As mentioned I'm **not** a fan, but perhaps it's just a matter of tweaking. IMO the current gray used looks slightly disabled. Here's a few quick ideas with less gray:

sidebar

I also see a minor issue with list that has disabled switches like dconf:

New:
image

Old:
image

**Comment by NusiNusi** [comment]
I like the white background with the black text. This way it looks connected to white field the folders are in.
The gradient looks good to. But i would say the gray should be on the left and the white on the right.

**Comment by Feichtmeier** [comment]
Well, no it's not too early. Since this PR is already merged (shame on me -.-) We need another issue and another PR after.
We need atleast an issue which indicates this bugs shown in your gifs and screenshots because otherwise they will get lost!
*(((super offtopic, but please check the community side didi has an important question there regarding the icon size)))*

**Comment by NusiNusi** [comment]
I am still waiting for the update on my snap-install. You too? Or is something broken on my install?

**Comment by NusiNusi** [comment]
I could test it now and... wow... it is amazing how professional and clean it looks:
bildschirmfoto von 2018-04-19 19-03-06
I would only recommend making the text and the icon pure black. @godlyranchdressing made a PR with white background and i am looking forward to test that one too. At the moment IMHO it looks very good and fits to the rest of the style. I would really only tweak with black text and symbol. But lets check the white background first. Thank you @godlyranchdressing

**Pull request merged**
