### PR TITLE
Added pressed effect on checked non-flat buttons

### LINKED ISSUE #457: Pressed toggle button has no hover effect
A toggle button that is toggled/active has no hover effect. This can be seen in `gtk3-widget-factory`. Press one of the toggle buttons (so that it looks sunken, and has a dark background) - if you move the mouse away from it then back over, the button no-longer gets lighter when the mouse passes over.

### PR DESCRIPTION
**Pull request by clobrano**
closes #457

### CODE REVIEW

**Comment by godlyranchdressing** [comment]
Can you post a GIF of it in action?

**Comment by clobrano** [comment]
Sure

button-hover-checked

**Comment by Feichtmeier** [comment]
peek 2018-05-22 22-33
The hover is very bright in the dark variant

**Comment by clobrano** [comment]
> But maybe this fits this PR? If not just ignore

I don't want to ignore :D but I prefer opening a new issue for that ;)

**Pull request merged**
