### PR TITLE
Added window controls boxed hover effect

### LINKED ISSUE #18: boxed hover effect on window control buttons
This idea comes from [madsrh's mockup](http://madsrosendahl.dk/ubuntu/mockup6.html).

box-hover-window-controls

It requires background-images for control buttons, so it's not a high priority task

### PR DESCRIPTION
**Pull request by clobrano**
closes #18

### CODE REVIEW

**Comment by galgalesh** [comment]
This PR had conflicts, I fixed them myself, but it might be best to check if that was correct.

There is a tiny issue: the "on click" state of the window controll buttons are different than the other headerbar buttons. Do you want to fix that now or should I merge it and create an issue?

peek 2018-01-21 12-48

**Comment by clobrano** [comment]
Oops, I prefer to fix that here

**Comment by clobrano** [comment]
Fixed now
boxed-hover-effect

**Comment by galgalesh** [comment]
Awesome :balloon:

**Comment by didrocks** [comment]
Excellent attention to details! Thanks to both of you @galgalesh  & @clobrano  ;)

**Pull request merged**
