### PR TITLE
Added back box-shadow to button in normal state

### PR DESCRIPTION
**Pull request by clobrano**
peek 2018-06-14 15-00

see #265

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr541`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr541` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
I think I have already expressed that I prefer the current version but why don't we use other methods to
a) indicate that buttons are clickable (like a colour difference)
b) differentiate buttons from entries with a change to entries
?
This looks a bit like the buttons are detached from the surface. Like when you lay a piece of paper uppon the table

**Comment by clobrano** [comment]
Plan A is the one we rejected considering that white buttons look better than gray ones
Let me try a little with plan B

**Comment by Feichtmeier** [comment]
Yes white can't become any brighter. But the background could be darkened a bit. When buttons have no box Shadow and only a little color difference to the surface I understand that some might say that they can not be identified as an clickable object (note: I don't mean hover). 
In the software main view three white objects have a good contrast on the grey area

**Comment by clobrano** [comment]
The problem is distinguish button from entries.

**Comment by Feichtmeier** [comment]
Yes this could be achieved by a super soft border-top increase and or inset box shadow but you prbly know :dancer:

**Comment by clobrano** [comment]
Here is a mockup applying to entries the same effect active buttons have

image

It looks a bit rough in the top right corner when in combo with a button and I am a little in favor of button change, but I have no strong preference

@madsrh what do you think about this?

**Comment by madsrh** [comment]
Well, this is hard 🤔 

I think the entry fields looks good, but on the buttons I would prefer some kind of shadow. I like the buttons [in the PR above](https://user-images.githubusercontent.com/2883614/41413554-bcf734ac-6fe3-11e8-9124-0d546ab41dc5.gif).

**Comment by Feichtmeier** [comment]
@clobrano I will not block this. Maybe everyone else is right. Usability > MostOtherStuff in the end. We got a big audience (ubuntu users) so better go for this!

**Pull request merged**
