### PR TITLE
Clean up + fix black text on orange bg issue in nautilus

### PR DESCRIPTION
**Pull request by godlyranchdressing**

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thank you very much :+1: 
Feel free to merge asap

**Comment by NusiNusi** [comment]
Can we test this via snap?

**Comment by Feichtmeier** [comment]
I am not sure. I fear not since he did the PR from his fork

**Comment by clobrano** [comment]
LGTM as well. Since this is a fix of previous problem, feel free to merge it IMHO

**Pull request merged**
