### PR TITLE
red close button only on hover and pressed

### PR DESCRIPTION
**Pull request by Feichtmeier**
Implementation of https://github.com/ubuntu/gtk-communitheme/issues/319

peek 2018-04-10 13-33

@clobrano please review, old code is commented

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@clobrano uhm, this is strange :D 
So after recent commit every application does
- light grey on all buttons only on hover
- red cross only on close button only on hover

EXCEPT gnome-tweaks:

peek 2018-04-10 15-54

**Comment by clobrano** [comment]
> What window state is only for gnome-tweaks?

There is no such thing :smile: 

Have you used gtkinspector on gnome tweaks maybe? That would avoid the application to acquire new changes on the theme.

**Comment by Feichtmeier** [comment]
Yes ofc, just though it would be good to get back! WIll do

**Comment by Feichtmeier** [comment]
Merging after email communication

**Pull request merged**
