### PR TITLE
New_green_selection_mode_checkboxes

### PR DESCRIPTION
**Pull request by Feichtmeier**
Closes https://github.com/ubuntu/gtk-communitheme/issues/236

- renamed the old adwaita checkboxes
- made new ones out of the existing ones in the shell repo

peek 2018-05-12 00-16
That's adwaita:
peek 2018-05-12 00-32

@madsrh @clobrano @godlyranchdressing as you can see both adwaita and now our checkboxes (I used all the names from adwaita) seem to "miss" 1 state. The moment when you press/long press the empty checkbox. For this moment there is no picture. But adwaita doesn't have it neither - so no idea how this state is called. :|
Either we push this now or wait until we found how it is named and prbly report it also upstream

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr436`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr436` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Great work @Feichtmeier 
I checked the missing icon with gtkinspector and it should be on state active:hover but I couldn't manage to make it work anyway. Probably we can report this upstream and ask them if we're doing something wrong or if it's a bug.
One last thing. Checkboxes look a little too big to me (gnome's one where smaller, with a transparent thick border). I think that changing `min-height` and `min-width` from 40px to 30px would be better

https://github.com/ubuntu/gtk-communitheme/blob/e552108d4c3cb20be8c83a1df3870f1114dc7d94/Communitheme/gtk-3.0/_common.scss#L2817
https://github.com/ubuntu/gtk-communitheme/blob/e552108d4c3cb20be8c83a1df3870f1114dc7d94/Communitheme/gtk-3.0/_common.scss#L2818

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr436`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr436` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
LGTM :+1:

**Pull request merged**
