### PR TITLE
Add bg color to selected list row

### PR DESCRIPTION
**Pull request by godlyranchdressing**
Addresses #376

### CODE REVIEW

**Comment by Feichtmeier** [comment]
We need a solution for all of these selected sidebar rows. They are also used in the software-center as screenshot thumbnails:
image

**Comment by clobrano** [comment]
@Feichtmeier that is probably due to the image being too close to the border of the row. I feel safe in accepting this change, selected row is at more visible now. What do you think?

**Comment by Feichtmeier** [comment]
Sure I like all of the selected rows we had (including the orange "Blob", the orange stripe and now this)
However: how should we fix this problem? I think it would be rather un-smart to Style the sidebar in a way that does not fit for every place it is being used. Otherwise we end up theming for specific apps
That's why I thought this would be a good timing or targeting a solution that works everywhere

**Comment by godlyranchdressing** [comment]
> We need a solution for all of these selected sidebar rows. They are also used in the software-center as screenshot thumbnails:

:sob: 

We can use `.image-list row` to make the software center ignore the orange strip, but who knows if there's some other app that will have a similar problem. The only other sensible alternative is to bring back the orange background color for selected rows.

> I think it would be rather un-smart to Style the sidebar in a way that does not fit for every place it is being used

I agree. It should "just work"

**Comment by clobrano** [comment]
> who knows if there's some other app that will have a similar problem.

That's the point. Probably, the easiest solution (orange selection) would be the one that fit best

**Comment by Feichtmeier** [comment]
We could use the full force selection again, yet with a different tone of orange? Like proposed in the selected text discussion?

**Comment by clobrano** [comment]
That is a possible solution, but maybe this time I'll try to produce a list of mockups to compare each other before going on the real thing

**Comment by godlyranchdressing** [comment]
@Feichtmeier I think it'll be safe to use the regular orange (#E95420) for the selected list row. If we so prominently use a different shade of orange then that'll open up the "then why don't we use it here too?" question and we'll get stuck again.

**Comment by Feichtmeier** [comment]
As long as we do not have a better solution that really works for every app I agree! @madsrh ? +1 -> merge
image

**Pull request merged**
