### PR TITLE
Menus again: Padding top bottom & no border radius for items

### PR DESCRIPTION
**Pull request by Feichtmeier**
werwerwer

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr531`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr531` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Paz-it** [comment]
I have a very weak heart, I can't believe it ..No no no...Please!  :hammer:

**Comment by clobrano** [comment]
@Paz-it no need to be so harsh.
@Feichtmeier I think I prefer current version, it is more distinctive respect other themes that uses it (except the one we borrow this from :D). The thing I like less is the effect with submenus.

**Comment by Feichtmeier** [comment]
This gif shows the standard how every other menu that uses round corners handles the menu entries and sub menus. I still can't decide whether our current approach is good design because no one else uses it or bad design because it looks weird

**Comment by clobrano** [comment]
Alright, so why don't we take some time to get use to it?

**Comment by clobrano** [comment]
Honestly, I don't see much difference in "selection visibility". I am not against this PR, but I'd like to keep the uniqueness in our menus highlight.

**Comment by Feichtmeier** [comment]
Being unique is a great thing, if the design makes sense and does not scare more people than it attracts people. The current master looks like bubbles in a bubble. Where this approach looks like stripes selected from a bubble. :man_shrugging: If I am really alone with this I give up. I just can't think that this would be welcomed by "neutral" people who haven't gone through all that menu changes we have went through. I believe we could have lost our neutral view on that when merging the last change I did which is in master now. I would rather go with the good looking (osx!) standard than a questionable uniqueness

**Comment by clobrano** [comment]
I didn't even participate in this change, so I think I am quite neutral :D

I like them both, if you are so strongly convinced, we can merge it

**Comment by madsrh** [comment]
@Feichtmeier I think it's nice that they are similar to the headerbar's menu, but this is not an achilles heel for me - fine with both solutions 🤷‍♂️

**Comment by Feichtmeier** [comment]
Na I won't force my opinion on you. Let's see what others say if they are still around:
@luxamman @godlyranchdressing

**Comment by Paz-it** [comment]
If my opinion can help to keep the current, I'll be more then happy. It's unique in a good way, clean and stylish. solving the issues of bleeding borders and so much better looking from the other themes in the examples above.

**Comment by Luxamman** [comment]
Well, after reviewing I would prefer the new way because this is also in line with the shell and other selected elements in lists. But should also be applied to the app menu list if changed.

**Comment by Feichtmeier** [comment]
@Luxamman you are talking about the gtk popups, aren't you? This one? : 
yaop

**Comment by Luxamman** [comment]
Yes @feichtmeier 
This also is not completely fitting with the actual rounden corner style it seems

**Comment by Feichtmeier** [comment]
Okay. I try to adapt them to the menu

**Comment by Luxamman** [comment]
Adapt to the actual or the proposed style?

**Comment by Feichtmeier** [comment]
To the menu of this PR. So we can test how it would look

**Comment by Feichtmeier** [comment]
image
I can remove the borde-radius for the selected modelbuttons but I can't remove the space
:| Seems like we'd need to stick with that either way. But they are something a little bit special because they can have buttons in them and other stuff

**Comment by Feichtmeier** [comment]
@Luxamman this does not seem to be possible because the popovers have more tha "just" menuitem labels. Those would need to stay as they are. Is this ok for you?

**Comment by Luxamman** [comment]
Can't test it at the moment, but if the others are okay with it we can test it in the field. If it is not working we still can reverse it - hopefully :)

**Comment by Feichtmeier** [comment]
Ofc we can revert it. That's why we use git :dancer:

**Comment by godlyranchdressing** [comment]
I much prefer this!

**Comment by Paz-it** [comment]
I'll love it much more if it will change back to have the left/right padding. (If it stays like this it will be the first thing I'll change in the final theme locally.) 
Let us be unique in the good way!

**Pull request merged**
