### PR TITLE
GTK2 updates

### PR DESCRIPTION
**Pull request by godlyranchdressing**
Very minor updates for gtk2 theme: Bluish bg, etc.

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr569`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr569` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Did anyone test this yet? @madsrh @clobrano 
Otherwise I am pretty sure we can merge it "blindly" since only assets are updated for gtk2 ? And some .regular-button for gtk3. What's that regular-button @godlyranchdressing ? :dancing_men:

**Comment by clobrano** [comment]
I'll test it right away

**Comment by clobrano** [comment]
Very nice work on buttons and other things :+1:

**Pull request merged**
