### PR TITLE
sidebar colors tweaks

### PR DESCRIPTION
**Pull request by clobrano**
Initially discussed in #407 and revived by [this comment](https://github.com/ubuntu/gtk-communitheme/pull/407#issuecomment-395594228)

But basically is because current mainview and sidebar and button (yes I know) look a bit dull.

---

**EDIT** still to be done: 
- [x] filechooser
- [x] treeview header button hover 
- [x] bug when right clicking a row in treeview 
- [x] fix sidebar backdrop

Here are a new attempt. Please make a long test, several pieces can be affected (One for all, the filechooser, that is to be fixed already).

image
image
image
image

Filechooser fixed
image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr532`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr532` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Paz-it** [comment]
All is good with sidebar colors (file chooser still looks odd). - Happy me! :)))
Flat buttons are burring  :((( :crying_cat_face:

**Comment by Paz-it** [comment]
@Feichtmeier, I Did like the sidebars colors and pale separators. 
I Did Not like the flat btns.

**Comment by clobrano** [comment]
> I Did Not like the flat btns.

You didn't? So you like it now? :D

Jokes apart, flat buttons are not the focus of this change

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr532`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr532` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Filechooser should be already ok

**Comment by Feichtmeier** [comment]
In the file chooser the table header has a border top. In Nautilus table view there is none
 I think it looks a bit broken without, don't you think?

**Comment by clobrano** [comment]
I understand, but filechooser however does not have tabs to deal with

image

image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr532`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr532` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr532`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr532` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
I really like this PR!

**Flat btns** 
Previously we had always 3 visible layers/levels of depth: The lowest level was a pressed btn, the middle level was the "surface", like containers, and the third and highest level were unpressed btns which did not receive any height change when they were hovered. Now we have only two visible levels: at first the highest level is the surface and btns (both on the same level now) but when you hover above the flat btns they receive a height update! Really nice - I :heart: it

**Sidebar border**
Very silent, yet visible change - just works. Nothing much to write!

**Treeview**
There seem to be a bug when right clicking a row in treeview:
wtf

**Comment by Feichtmeier** [comment]
Everything becomes lighter. Doesn't the sidebar become lighter? Can't check ATM.

**Comment by madsrh** [comment]
> Everything becomes lighter. Doesn't the sidebar become lighter? Can't check ATM.

peek 2018-06-10 11-59

**Comment by Feichtmeier** [comment]
That's definitely darker!

**Comment by clobrano** [comment]
Yes I can surely let sidebar begin less dark in backdrop, but since we have both bright and dark colors, it is not feasible use the same transition function to change all. For example, the white main view cannot become brighter (nor more transparent). I think the best we can do is to keep the same color relationship between widgets

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr532`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr532` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Nice fixes!

One last thing: isn't the border color used for the tab (and prbly used for the rest, too) a bit too light now?
image
For screens with a not so good contrast it could be already invisible. I know you must be feeling like going back and forth but I was not the one who requested the super light borders, so I am not guilty! :laughing: 
*looking at someone else in the room*

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr532`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr532` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Nice, I'd +1 this =) Let's wait for mads ofc

**Comment by madsrh** [comment]
+1 😄

**Comment by madsrh** [comment]
@clobrano is it deliberately that buttons doesn't change on hover (except for the box-shadow)? Should there be a subtle gray on hover?

buttons

**Comment by clobrano** [comment]
Previously they got brighter, so now that are brighter by default the effect is lost. The old proposal with white button didn't have any color change and, in the past, we saw that gray on hover looked a bit dull, but maybe I can try with a very little color change

**Comment by Feichtmeier** [comment]
Are the buttons completly white now? Otherwise I would rather brighten them a tiny bit. That's what I am doing in the darktheme branch at least :D

**Comment by madsrh** [comment]
> ...but maybe I can try with a **very little** color change

**+1**

**Comment by Feichtmeier** [comment]
@clobrano could you tell me that change so my darktheme branch won't get conflicts with your branch then? :D I am quiet sure this will crash as these should be the same lines

**Comment by clobrano** [comment]
Sure, but with a git rebase you should be safe :)

**Comment by clobrano** [comment]
Sure, it will show you where the conflict is, if any

**Comment by Feichtmeier** [comment]
Since closed PR's are the shit of communication ;D I am going to make yet another post here:
@clobrano @madsrh how about rather than darkening the color on hover we could increase the strength of the borders a little bit more on hover?

**Comment by madsrh** [comment]
> how about rather than darkening the color on hover we could increase the strength of the borders a little bit more on hover?

Let's try it. Do you have a gif?

**Comment by Feichtmeier** [comment]
41165206-5b5ad492-6b3d-11e8-9d7b-7af4084f4afe
Hm like this? Or maybe that's too much? That's 20% darker than master

**Pull request merged**
