### PR TITLE
Fixes to headerbar widget and borders

### LINKED ISSUE #378: Infobar buttons and selection-mode-titlebar could use some love
screenshot from 2018-04-28 19-38-00

The buttons could use a different solution when pressed:
image

The borders could look a bit better when attached to the half of the screen:
image

It's called selection-mode titlebar of the object gtkheaderbar

The buttons could be changed by @godlyranchdressing while the titlebar could be changed by @clobrano due to their/your recent PR-knowledge ;O

((maybe one coud fix thix issue in the same PR: https://github.com/ubuntu/gtk-communitheme/issues/236))

### PR DESCRIPTION
**Pull request by clobrano**
- styled buttons when headerbar is in selection-mode (green buttons)
- removed black border from headerbar in selection-mode
- fixed missing left dark border in headerbar when maximized (not selection-mode)

closes #378, addresses a problem introduced with #371

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Gnome software is also affected which uses the regular gtk.css

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr387`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr387` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
> Gnome software is also affected which uses the regular gtk.css

doh!

**Comment by clobrano** [comment]
Now should work better

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr387`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr387` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Pull request merged**
