### PR TITLE
Rework backdrop state

### PR DESCRIPTION
**Pull request by clobrano**
Review of:
- label colors for button and entries in backdrop (inactive) state
- spinbutton (horizontal) increase/decrease button
- check/radio button

Before
image

After
image

### CODE REVIEW

**Comment by clobrano** [comment]
see #341, however I forgot to fix menu labels

**Comment by godlyranchdressing** [comment]
I think these are too many changes to fix the problem. The issue started with the changes made on lines 62 and 63 in 8c20c5fdbd39a045359db908c04307e00aeeab58. Reverting those lines fixes things without having to make new lines in _common.scss that might not fix any issues we aren't seeing right now.

**Comment by clobrano** [comment]
Alright, I'll try to minimize the change. However, most of the lines introduced backdrop for checks and radio

**Comment by clobrano** [comment]
Let's drop this PR, I am going to open a new one

**Pull request closed without merging**
