### PR TITLE
Restyled drop-active box-shadow ring on nautilus tab

### LINKED ISSUE #605: Problem with drop target in Nautilus
Not sure if already known bug.
If I try to drag&drop a file onto a tab in Nautilus there's a rectangle with green border indicating I can drop it here. The problem I see is that rectangle partially covers the close icon in the tab. 
Please see the screenshot:
zrzut ekranu z 2018-07-04 11-56-11

### PR DESCRIPTION
**Pull request by clobrano**
closes #605 

peek 2018-07-09 15-25

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr616`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr616` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Looks good @clobrano 
Should we investigate something else than green and do you have something in mind?

**Comment by clobrano** [comment]
I think we should keep green, since it has a meaning here. BTW with rounded corners I can live with it :smile:

**Comment by madsrh** [comment]
@clobrano Much worse is the sidebar drag-drop green/orange, but I agree that we should leave this for now. Sorry for the PR noise ;)

**Comment by clobrano** [comment]
What noise? ;)

**Pull request merged**
