### PR TITLE
Round out dialog boxes and remove headerbar

### PR DESCRIPTION
**Pull request by godlyranchdressing**
Remove the dark titlebar from dialog boxes
Round out the bottom corners
Add a border for better window distinction

dialog

### CODE REVIEW

**Comment by clobrano** [comment]
Why removing the dark titlebar?

**Comment by godlyranchdressing** [comment]
darktitlebar

Looks like a waste of space. The seamless look that even Adwaita has looks much nicer.

adwaita

**Comment by Feichtmeier** [comment]
Though I followed the discussion and the poll on this topic, I agree that the black header bar is a bit pointless. On the one hand it is on par with the rest of the non-shell windows, but on the other hand there is nothing to click, and it is indeed wasted space. Also, I can imagine that people who did not follow the decision could think that there is something broken. Headerbars usually atleast have *something* inside of them to click :)

**Comment by CDrummond** [comment]
Without the headerbar, you cannot (easily) move the dialog. (I know you can use meta+left click, but not as convenient).

**Comment by clobrano** [comment]
I understand your point, but at the same time we specifically put that dark titlebar to have the same look for all the windows. @madshr?

**Comment by madsrh** [comment]
@godlyranchdressing Please backlog [the discussion here](https://community.ubuntu.com/t/mockups-new-design-discussions/1898/262).

I suggested this change because the white dialog doesn't fit well with the rest of the theme and adding a headerbar seems more visually consistent to me.

I still believe that, but I've also had second thoughts about this: My biggest concern, after pushing for this, is that every other OS (_OSX, Windows, Android,..._ ) uses the plain white box 🤔

Can we leave this in for a while and see if we(read I) will be burned on the forum? 🔥I would like to discuss this and [the dark dialogs](https://github.com/ubuntu/gtk-communitheme/pull/153) with Canonical design / UX team, but I think they will be too busy until 18.04 is out.

@clobrano What do you think after using this for 2-3 weeks? I'm guessing you @godlyranchdressing are **-1** 😉 

@Feichtmeier It was very wrong of me to create a poll about this 😞I just wanted to know what people thought would match the theme, but it seems some people believed that we would implement the design with the most votes.

**Comment by Feichtmeier** [comment]
Hm, shouldn't we start from the default settings though? Only because one can move the dialog with a setting the design should not be centered around this option. Those two button dialogues are there for two actions. Accept or cancel. I believe the gnome designers had exactly this in mind when designing those adwaita theme settings.

**Comment by clobrano** [comment]
> I still believe that, but I've also had second thoughts about this: My biggest concern, after pushing for this, is that every other OS (OSX, Windows, Android,... ) uses the plain white box

Is it possible to know whether those plain white box are system notification or theme notification? We still have plain (black) boxes for system ones

> @clobrano What do you think after using this for 2-3 weeks? I'm guessing you @godlyranchdressing are -1 wink

I think I get used to it, and I like it better now

> Without the headerbar, you cannot (easily) move the dialog.

This is my main concern for this change, actually. If you select this option and move the main window what happens? The main window moves and the modal dialog does not?

**Comment by CDrummond** [comment]
@clobrano With these dialogs open, you cannot move the main window - regardless of whether `Attach modal dialogs` is set or not.

**Comment by clobrano** [comment]
Alright then, to me, if the system allows you to move any window, the theme should support it. In fact originally the window was a white box, but with a titlebar

**Comment by CDrummond** [comment]
I would imagine this is not possible to do but... Perhaps if `Attach modal dialogs` is enabled (the default setting), then there should be no titlebar. If its disabled, then there should be a titlebar (and more shadow)?

But, seeing as the theme is CSS, I'd image this is impossible to do.

I'm coming round to the idea of no titlebar. Because, with the default setting of `Attach modal dialogs`, if you attempt to move the dialog then the **whole** window moves.

**Comment by Feichtmeier** [comment]
With the default setting if you move the dialog the window AND the dialog move in one:

peek 2018-03-25 12-15

**Comment by nana-4** [comment]
I really can understand @Feichtmeier's points of his first comment, but somehow I like the current style better than the plain white box.

How about simply reducing the titlebar height?

image

This can save space and should resolve the concern (from @Feichtmeier's comment):

> can imagine that people who did not follow the decision could think that there is something broken.

**Comment by Feichtmeier** [comment]
I have to admit that I still think that the previous version which looks like the shell dialogs, without free space between the buttons and with the wide buttons looked "better" and more to the point. At the moment they look almost like there are some elements missing (to me). I don't know why, maybe I've looked to long on the prev version/shell dialogs :)

**Comment by madsrh** [comment]
@godlyranchdressing please see https://github.com/ubuntu/yaru/issues/698

**Pull request closed without merging**
