### PR TITLE
Use transparent inset shadows instead of dashed lines for undershoots

### PR DESCRIPTION
**Pull request by Feichtmeier**
Closes https://github.com/ubuntu/gtk-communitheme/issues/523

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr527`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr527` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
It's subtle, but very slick +1 from me.

@clobrano ?

If the scrollbars didn't autohide, we wouldn't need this in the first place 😉

**Comment by clobrano** [comment]
Very nice indeed. Would it be possible to try a shadow a little wider and brighter/transparent? If not, I'm glad to accept this one

**Comment by Feichtmeier** [comment]
More transparent is still possible.
Wider could be hard but I try.
It's actually a "cheat" because that undershoot seems to be technically a box. If you use the blur or spread from inset box shadow the box is getting the shadow and not only the edge. So I use two shadows for each edge, 1 at pixel 1 and 1 and pixel 2. I could add a third at pixel 3. I try and post gifs before commiting

**Comment by Feichtmeier** [comment]
More transparency is not really possible :D or I changed the color :thinking: 
That's 0.8 (current):


That's 0.9 and the shadow disappears:

And that's with three shadows:
3shadows

**Comment by clobrano** [comment]
I think the current one looks good enough :+1:

**Comment by Feichtmeier** [comment]
Okay, we can tweak it later if we have more ideas. Maybe you have one when you look into the implementation which is a bit "weird" :smile:

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr527`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr527` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Pull request merged**
