### PR TITLE
Update checkbox, radio, switch, spinner & scrollbar to resemble Suru's

### PR DESCRIPTION
**Pull request by godlyranchdressing**
Updated each element to look more like Suru's. Closes issue #14

More can be seen here: [scrollbars](https://docs.ubuntu.com/phone/en/apps/design/building-blocks/scrolling), [switches, checks, etc.](https://docs.ubuntu.com/phone/en/apps/design/building-blocks/selection-controls).

### CODE REVIEW

**Comment by galgalesh** [comment]
Ps: if you write 

```
Closes #14
```

On a line by itself in the description of your prompt, that issue will be auto closed when the or is merged.

More Info: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by godlyranchdressing** [comment]
Ohh. I noticed I'd close them _occasionally_ when writing that in a commit, I didn't figure out that it had to be on a separate line though, thanks!  :laughing:

The last commit updates the stackswitcher and pathbar buttons to match these mockups:

[Pathbar](https://ubuntucommunity.s3-us-east-2.amazonaws.com/original/2X/e/e1415d5578303303f2d59f54999f23989e47bcf3.png)
[Stackswitcher](https://ubuntucommunity.s3-us-east-2.amazonaws.com/original/2X/8/8c06576240ecb8594e29ec434a574dca28b7ed36.png)

**Comment by galgalesh** [comment]
Looking good! :1st_place_medal: Merged.

Is it intentional that the pathbar has a different color than the mockup? (top is mockup)

image

Also, Ubuntu Software and a bunch of other programs have stackswitcher-like buttons but they look differently. Is this supposed to be the case?

image

**Comment by didrocks** [comment]
Maybe you should file those as bugs ? (as you commented after the PR was merged)

**Comment by galgalesh** [comment]
Follow up happened in differen PR's; the second issue has been fixed by PR https://github.com/Ubuntu/gtk-communitheme/pull/23 and https://github.com/Ubuntu/gnome-shell-communitheme/pull/8.

I actually don't think the first one is an issue because the actual implementation is more consistent than the mockup: "active" buttons are a bit lighter than "disabled" buttons. Now the pathbar also follows that logic. @godlyranchdressing can you confirm that this is what is supposed to happen?

**Comment by didrocks** [comment]
Excellent, you are on top of what's happening, thanks a lot! :)

**Pull request merged**
