### PR TITLE
Adjust main view and sidebar colors

### PR DESCRIPTION
**Pull request by clobrano**
- made sidebar brighter than main view (this revert a previous change)
- made bg_color a little darker and button bg brighter
- made headerbar backdrop bg color a little brighter to improve visibility
- made sidebar-to-main-view separator more transparent

image

image

image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr407`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr407` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr407`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr407` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by godlyranchdressing** [comment]
Is this to fix a bug? I'm not usually one to see things as too bright, but this looks a little too bright. :grin:

**Comment by madsrh** [comment]
> @madsrh was talking about...

I was? 🤔 

I don't recall. If this was back in December it dosen't apply anymore 😜 but I do agree with @godlyranchdressing that this seems a bit bright at first sight (I haven't tried it yet, only screenshots)

**Comment by madsrh** [comment]
BTW, I'm glad that you tried the brighter backdrop headerbar 👍 IMHO you can brighten it a notch more.

**Comment by clobrano** [comment]
> I was? thinking

Yup, on the forum, but maybe I misunderstood :D

However, are you OK in inverting this colors or do you prefer sidebar darker than main view?

**Comment by madsrh** [comment]
@clobrano This is a completely different experience. I might be influenced by the current design (which I really like :anguished: ), but it feels like the weight if off - as the focus is on the sidebar.

I do prefer the current, but I would like to try this one for a some time if you feel it's a better suggestion, but this PR removes the wallpaper, so it's kind of distracting 😆 

image

**Comment by clobrano** [comment]
I don't even know how this is possible 🤣 
Let me try the snap on VM

**Comment by madsrh** [comment]
> made headerbar backdrop bg color a little brighter to improve visibility

Any change you could move this one into a separate PR ? I'm not sure about the others, but I would like to merge this one 😃 

Perhaps even **7%** 

 `$backdrop_headerbar_bg_color: lighten($headerbar_bg_color, 7%);`

**Comment by clobrano** [comment]
Of course :)

**Comment by clobrano** [comment]
Considered the new change on dark version and hoping in the comment below :smile: 

> I do prefer the current, but I would like to try this one for a some time if you feel it's a better suggestion, 

I reopen this PR. Please consider it a real mockup and a bland suggestion. Do not merge it easily :)

**Comment by madsrh** [comment]
I tried this for a bit, and I can't get used to the bright sidebar 😕

@godlyranchdressing what are your thoughts?

**Comment by clobrano** [comment]
> I tried this for a bit, and I can't get used to the bright sidebar

Is that everywhere or only in nautilus? Since I think that nautilus should actually have sidebar darker.
However, my other main goal here was to bring back brighter buttons :)

**Comment by Feichtmeier** [comment]
I find it very interesting that while I believe the "lighter sidebar/ darker view" approach works very wellon the dark theme does not seem to work for the light theme :thinking"
It's just no linear system. I think light and dark need individual solutions at some places

**Comment by clobrano** [comment]
I understand, I get used to this version, even if it's a bit boring, I don't know how to explain it better :)

No problem, I can close it again

**Comment by madsrh** [comment]
### Hey! 
Just a few thoughts 💭 

I've been looking at **Arc Darker** which I think look really modern and uses the same white/gray split as this PR:

image

...and there's few differences here:
- The gray background is brighter!
- Buttons are smaller and completely flat
- Nautilus is styled with a dark sidebar

image

As mentioned, I'm happy with our current design, but I do still think that our current gray buttons gives it an old-school look (not as much as earlier though).

**Comment by clobrano** [comment]
I agree with the point of view regarding buttons, this PR was also to have a darker background (respect master) so that buttons can be brighter. 
Nautilus can be different than settings or other apps with a sidebar, but I'd like to play again with sidebar/mainview colors.

**Comment by clobrano** [comment]
Rebasing this branch on master would be too long, I'll open a new PR with the new version of this change, which looks like this

sidebar-color-review

**Pull request closed without merging**
