### PR TITLE
Add scrollbar arrows, so that QGtkStyle has pixmaps to draw.

### PR DESCRIPTION
**Pull request by CDrummond**
QGtkStyle can be used by Qt apps so that they use Gtk2 to draw the widgets. Unfortunately, QGtkStyle is hard-coded to assume that scrollbars have steppers/arrow buttons.

This modification configures the pixmaps to use for these arrows, so that Qt does not just draw an empty area.

The arrows are V shaped - as these were the only pixmaps I could find to fit (the ones from Communitheme are too large).

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thank you very much for stepping up and contributing code this is a real help since I have zero experience in Qt and gtk2

**Comment by clobrano** [comment]
Thanks @CDrummond! How we could test this? or, could you post a picture of an app without and with this change?

**Comment by CDrummond** [comment]
To get a Qt app to use the QGtkStyle plugin (so that it uses Gtk2 to draw the widgets), you need to have `qt5-style-plugins` installed. You can then start a qt5 app as follows:

```
QT_QPA_PLATFORMTHEME=gtk2 /usr/lib/x86_64-linux-gnu/qt5/bin/qdbusviewer
```

QDbusViewer before change:
before

...and after change:
after

This is really only a work-around for QGtkStyle deficiencies - but its had these issues for quite a while, and (AFAIK) is no longer actively maintained. Kvantum would be nicer, but that's a no go due to licensing :-(

**Comment by clobrano** [comment]
Probably I made some mistake, here is my output
```
QT_QPA_PLATFORMTHEME=gtk2 /usr/lib/x86_64-linux-gnu/qt5/bin/qdbusviewer
/usr/share/themes/Communitheme/gtk-2.0/main.rc:409: Unable to locate image file in pixmap_path: "assets/scrollbar-arrow-up.png"
/usr/share/themes/Communitheme/gtk-2.0/main.rc:414: Overlay image options specified without filename
/usr/share/themes/Communitheme/gtk-2.0/main.rc:418: Unable to locate image file in pixmap_path: "assets/scrollbar-arrow-down.png"
/usr/share/themes/Communitheme/gtk-2.0/main.rc:423: Overlay image options specified without filename
/usr/share/themes/Communitheme/gtk-2.0/main.rc:427: Unable to locate image file in pixmap_path: "assets/scrollbar-arrow-left.png"
/usr/share/themes/Communitheme/gtk-2.0/main.rc:432: Overlay image options specified without filename
/usr/share/themes/Communitheme/gtk-2.0/main.rc:436: Unable to locate image file in pixmap_path: "assets/scrollbar-arrow-right.png"
/usr/share/themes/Communitheme/gtk-2.0/main.rc:441: Overlay image options specified without filename
Gtk-Message: 20:26:01.263: Failed to load module "canberra-gtk-module"
```
and I don't see the arrows

**Comment by CDrummond** [comment]
Ah, that's because I forgot to update the meson build file! Sorry, I originally did this on a checkout from the main repo - and forgot to copy that change!

**Comment by clobrano** [comment]
Awesome, that did it. Thanks :+1:

**Pull request merged**
