### PR TITLE
Rework/backdrop state

### LINKED ISSUE #212: Separation between active and passive (backdrop) windows is very harsh
As posted by @Luxamman (https://github.com/Ubuntu/gtk-communitheme/issues/194#issuecomment-368857266):

> The passive windows are tricky, I had to rethink them a little because the separation between active and passive windows is very harsh.
> 
> This is especially irritation when working with two windows side by side (something very common I think) - because passive windows look almost like deactivated or like they hung up.
> 
> Like in other systems, it is good to give a hint which window is passive (like windows control orange getting grey and headerbar little lighter, and content colors getting brighter or grey), but maybe we should not separate the whole content and buttons too hard.
> 
> When windows are stacked, they have separation lines and a shadow to be visually separated - so I'm with you to reduce the overall passive look - including buttons and content.

### PR DESCRIPTION
**Pull request by clobrano**
New backdrop state in order to reduce the difference against normal state.

image

current normal state is
image

closes #212

### CODE REVIEW

**Comment by godlyranchdressing** [comment]
This looks much nicer! I kind of miss the desaturation of colors (orange, green, etc.) though, but I could live without it.

**Comment by clobrano** [comment]
I replaced desaturation with darkening (is it a valid word?) so that it could be used in more places, simplifying the change and improving consistency

**Comment by madsrh** [comment]
Great work @clobrano (that was fast). I can't wait to try this :clap:

**Comment by didrocks** [comment]
Couldn't say better :)

**Comment by madsrh** [comment]
@clobrano Any chance that a color overlay could be added to the icons as well? Currently they have the same color as the active window:

backdrop

**Comment by clobrano** [comment]
Not sure, I'll check this

**Comment by clobrano** [comment]
Sorry for the late reply. I tried using old "active" png for this, but are we sure we want more orange now, considering current trend? :smile:

**Comment by madsrh** [comment]
If that was for me @clobrano, I didn't understand it. I was asking about darker icons in backdrop.

**Comment by clobrano** [comment]
Oh my, too much jumping from bug to bug, totally forgot what you were asking for :smile:

**Pull request merged**
