### PR TITLE
Pathbar and stackswitcher updates

### PR DESCRIPTION
**Pull request by godlyranchdressing**
- Path-bar buttons all have a shared background color

### CODE REVIEW

**Comment by clobrano** [comment]
Arrows in path-bar do not have any hover effect, is that on purpose?

**Comment by godlyranchdressing** [comment]
Yes, they're aren't checkable buttons and the underline effect is only reserved for checkable buttons. If we want them to have some type of color feedback we could make the arrows themselves turn orange.

**Comment by clobrano** [comment]
The only problem to me is the missing feedback when hover on the arrows, so maybe it's better with an orange color

**Comment by godlyranchdressing** [comment]
This is a silly question, but how do you get the arrows to function? They're always disabled for me.

**Comment by galgalesh** [comment]
open a long path and make the window of nautilus small so the path can't fit in the header completely.

**Comment by clobrano** [comment]
LGTM 👍

**Pull request merged**
