### PR TITLE
Join message dialog buttons (like in ambiance)

### PR DESCRIPTION
**Pull request by godlyranchdressing**
dialog buttons

### CODE REVIEW

**Comment by clobrano** [comment]
Not sure about that. Maybe separated works better

image

image

**Comment by clobrano** [comment]
Hey @madsrh, @Luxamman,
what is your opinion on this?

**Comment by madsrh** [comment]
I don't like the joint version. Separated works better

**Comment by clobrano** [comment]
Alright, closing it then

**Pull request closed without merging**
