### PR TITLE
Darker blue text selection for entries in headerbar

### PR DESCRIPTION
**Pull request by Feichtmeier**
Closes https://github.com/ubuntu/gtk-communitheme/issues/574

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr575`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr575` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
@Feichtmeier I think the idea "Darker blue text selection for entries in headerbar" idea is good 👍  but I think we need to tweak the blue IMO.

The blue in this PR (+dark theme) really jumps in my eyes - it's very bombastic in lack of better words. Kind of the same problem that made us switch away from full orange.
It also seems to be brighter than the slider blue. Is this intentionally?

image

I would like to see it less shiny, more dull in the direction of #48b0d4.

I know it's and another issue. What do you think?
image
image

**Comment by Feichtmeier** [comment]
Okay I try that later! :)

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr575`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr575` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr575`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr575` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
I thought it said:

> Make blue less **pooping**  

💩🤣 

This one looks good IMO. Can we merge it, or do you want +1 from @clobrano too?

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr575`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr575` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr575`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr575` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Clearly not the right way of changing the code, but I tried it and although the colors were good, the text was much harder to read. This one is somewhere in between:

- [New PR suggestion](http://jxnblk.com/colorable/demos/text/?background=%2348b7de&foreground=%23202020)
- [Edge](http://jxnblk.com/colorable/demos/text/?background=%2348c5f2&foreground=%23141414)
- [Pooping suggestion](http://jxnblk.com/colorable/demos/text/?background=%2348b0d4&foreground=%23202020)

**Comment by Feichtmeier** [comment]
We can just do it in this pr I think if you have other suggestions :)

**Comment by madsrh** [comment]
I don't have other suggestions. I'm happy with this one now 😀

**Pull request merged**
