### PR TITLE
Moved_logic_back_to_the_draw_circle_mixin

### PR DESCRIPTION
**Pull request by Feichtmeier**
- removed unnecessary lines in common
- added the new design to the draw circle mixin
- this fixes a small black circle delay -> Closes https://github.com/ubuntu/gtk-communitheme/issues/402
@clobrano correct me if I am wrong =) because you opened the issue before the "newer" design
peek 2018-05-12 14-53

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr437`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr437` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
LGTM :+1:  nice work!

**Comment by godlyranchdressing** [comment]
It could be an illusion because of the icon, but the close button in backdrop looks too light.

**Comment by clobrano** [comment]
@Feichtmeier could you double check this? It looks as @godlyranchdressing said to me as well

image

**Pull request merged**
