### PR TITLE
Restyle buttons

### LINKED ISSUE #278: The current button design doesn't work well with linked buttons
Another **very** minor niggle. The shadows under buttons look great, but with split buttons the shadow does not extend between the buttons. It looks as if the shadow is per button. Screenshot is an `xmag` capture from `gtk3-widget-factory`

As stated, very minor niggle - feel free to ignore.

screenshot from 2018-03-23 07-52-43

p.s. Sorry for reporting such minor issues - just this is shaping up to be the best theme I've ever seen :-)

### PR DESCRIPTION
**Pull request by nana-4**
- Make the background a little bit darker
- Restyle buttons
- Fix excessively long transition of buttons
- Remove inner box-shadow of entries
- Fix button/entry sizing
- Fix frame border-color

See #288
Closes #278

### CODE REVIEW

**Comment by NusiNusi** [comment]
Can we test it this way?:
``snap refresh communitheme --channel=edge/gtk-communitheme-pr331

**Comment by Feichtmeier** [comment]
Nice! Indeed that was the strength of snap in the end. Did not work though. @didrocks please help us to test this PR! :dancer:

**Comment by nana-4** [comment]
@Feichtmeier If your remote repository has been named `upstream`, run:

```
git fetch upstream pull/331/head:restyle-buttons
git checkout restyle-buttons
```

then compile as usual. I think this will work well. :)

**Comment by madsrh** [comment]
Sure 👍 
I asked in the "Light app notifications" PR, but can I merge this even though it says "The Travis CI build failed"?

**Comment by Feichtmeier** [comment]
Yes, I believe the CI builder is here for the snapping. @didrocks any comment on this?
The past two sites of closed PRs failed all except one by didi :D

**Comment by didrocks** [comment]
(discussed directl on the forum)

**Comment by Feichtmeier** [comment]
@didrocks yes this is older than our conversation =)

**Pull request merged**
