### PR TITLE
Round titlebuttons, orange close button

### PR DESCRIPTION
**Pull request by godlyranchdressing**

### CODE REVIEW

**Comment by Feichtmeier** [comment]
I guess there are still commits coming?
image
I pretty hot for this :O

**Comment by godlyranchdressing** [comment]
What the hell. That wasn't happening just a minute ago.

**Comment by Feichtmeier** [comment]
@madsrh how about trying the following pressed header bar button in the change/thisPR of circle close/max/min buttons (so squircle/circle won't be there):
screenshot-20180429102941-1252x894

**Comment by Ads20000** [comment]
After reading [this post](https://design.canonical.com/2016/05/colour-palette-updates/) (and other Unity 8 design posts) I'm not sure about making the orange always visible, it is rather attention-grabbing, hmm... Up to you lot I guess, just offering thoughts... I think orange (or potentially red) on hover makes sense... but the background grey squircle and orange circle doesn't make much sense to me. How about attempting an orange squircle? :)

**Comment by godlyranchdressing** [comment]
@Feichtmeier I've solved the backdrop issue so we can merge this if everyone is okay with it.

**Comment by Feichtmeier** [comment]
Yes let's try it

**Comment by clobrano** [comment]
We might have lost a bit of pressing area here, which makes press these buttons less easy

**Comment by madsrh** [comment]
Could someone post a screenshot?

> We might have lost a bit of pressing area here, which makes press these buttons less easy

We want touch friendly sizes 😃

**Comment by godlyranchdressing** [comment]
It's the same size as the other buttons. 

Using box-shadow to show the actual size of the button:

title

**Comment by yousuc** [comment]
I personally prefer the rounded square vs the circles. Looks to osX'ish and too much like current ubuntu default.

**Pull request merged**
