### PR TITLE
darktheme introduction and light theme improvements

### PR DESCRIPTION
**Pull request by Feichtmeier**
@madsrh @clobrano please test the dark version with apps that use the dark theme by default like
GNOME
videos ("totem")
eye of gnome (that picture viewer)
boxes (virtualization software)
peek
todo (if you activate the dark theme in appmenu-> extensions)

Updating the gifs and pictures with every commit to be up to date:

Filechooser:
image
filechooser

Boxes:
image
boxes

Eye of gnome (image viewer):
image
eog

Pitivi:
image
pitivi

Todo:
image
todo

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr444`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr444` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr444`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr444` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Need more time for the backdrop though! So don't merge yet!

**Comment by clobrano** [comment]
Just a note then. Looking at the pictures, the GNOME Todo button "personal" in the first image doesn't look finished

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr444`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr444` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
General GNOME ToDo theming fixes incoming 
image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr444`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr444` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr444`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr444` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@godlyranchdressing 
sidebar_bg_color looks actually better in both themes in the treeview header. 
image
Before we had three colors mixed in the which looked a bit too much for my taste

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr444`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr444` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr444`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr444` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@godlyranchdressing just to give you some idea behind the commits:
- https://github.com/ubuntu/gtk-communitheme/pull/444/commits/5c8267177c93875dfe97c68d924df4c35b87caa7 icon opacity was also a revert of the changes that have been made in the process of that "orange stripe" trip we did with nautilus =) and looks very good in both bright and dark of the treeviewer and filechooser/nautilus
- the treeview row buttons looked very strange with a third color thus I limited it to two colors
- and the rest was gnome todo theming
- I separated the bg and base colors after your comment for dark a little tiny bit, but you can't play as much with the tone as with the light theme if you go to dark everything looks messy
- this was a bug fix for gnome boxes: https://github.com/ubuntu/gtk-communitheme/pull/444/commits/48acb3277555d31b6c374f52a04fa8821bd6646a
- and this one https://github.com/ubuntu/gtk-communitheme/pull/444/commits/bc51b099d28a30d4addb123c7fa983715168c092 was more of a correction since we used some darkening instead of the backdrop color there, and both dark and light versions profited of this commit

So what exactly do you mean? :)

I like the result very much, the only thing where I am very unsure is the way I themed gnome to do or the place, I wonder if there would be a better place but I didn't find any in common - could you help me with that?

**Comment by Feichtmeier** [comment]
@godlyranchdressing 
@godlyranchdressing 
Edit: same color as the table for the header, adwaita has the same solution:
screenshot from 2018-05-17 19-42-00
screenshot from 2018-05-17 19-41-56

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr444`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr444` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@clobrano thanks =D
Fixed the placesview (it's not eye of gnome specific that's the filechoser's placesview:
image

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr444`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr444` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr444`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr444` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Looking at your dark theme [here](https://github.com/ubuntu/gtk-communitheme/pull/444#issuecomment-389563106) @Feichtmeier, I wondered it would be better to do something like this: 🤔 

dark

**Comment by Feichtmeier** [comment]
@madsrh it looks nice in the file chooser! Do you think if we do this color switch we should do it in every app or just in the file chooser / nautilus?

**Comment by Feichtmeier** [comment]
Oh btw you took the old screenshot. Sorry. Updated at the top and at the bottom but not in the middle -.-
These are up to date: https://github.com/ubuntu/gtk-communitheme/pull/444#issuecomment-389950828

**Comment by Feichtmeier** [comment]
I love the idea!

image

The good thing with this color switch is, that the headerbar does not merge that hard with the dark sidebar this way! I will test this with other apps this looks very promising

**Comment by Feichtmeier** [comment]
@madsrh updated the initial post with your new nice idea - it works with every app!
I only need a solution for the hover color now. It is way too light

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr444`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr444` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Nice :) what about inverting colors in light version as well? :D

**Comment by Feichtmeier** [comment]
@madsrh @clobrano okay please try this PR or just look at the gifs/pictures in the OP - I'd like to merge this now and test it with more people so we can address individual issues ... individually =] Mostly more people notice more things!

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr444`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr444` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Hey 😃 Nice work @Feichtmeier 
You can merge this one, but I would like to see a darker sidebar and a slightly darker canvas (is that the name for the container with the files?) and a slightly lighter headerbar. Here is the PR444 compared to my mockup:

As you know I haven't tried this for more than a few minutes, so my suggestion is to be taken with a grain of salt. Apps like Gedit look great with this PR444

image

**Comment by Feichtmeier** [comment]
Alright thanks for the feedback. I would not go more dark because everything becomes a bit hard for the eyes (at least for my eyes =P)
I merge this now with a last mark for what's still to do / think about in the future:
- darken the hover color for not-header-bar-buttons in the dark variant
- lighten all header-bars a bit 
- double check every dark app for contrast and text color

**Pull request merged**
