### PR TITLE
wm_border left and right for dark theme

### PR DESCRIPTION
**Pull request by Feichtmeier**
Closes https://github.com/ubuntu/gtk-communitheme/issues/580

screenshot from 2018-06-29 01-34-59

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr581`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr581` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
Nope this is the only way to change all (not only CSD) windows but not touch the light context menus.
But are you okay with the color of the border? It's some kind of transparent black. Would be great if you would finalize a decision for both the border of the window + menu for the dark theme. Maybe you would find a solution for all borders in the dark theme? @madsrh

**Comment by madsrh** [comment]
This looks very good!!!

Two things:
1. The darker border looks good, but other places use a light border. Should they be the same?

image

2. The label in the right bottom in Nautilus now has two borders. Can we only have top and left border here?

image

**Comment by Feichtmeier** [comment]
That's a good question. Since the dark gtk and dark shell popups have a different look maybe this is something to remind for https://github.com/ubuntu/gtk-communitheme/issues/585

I personally like the difference between the shell and the gtk theme, but this is just me so maybe we should discuss the general look on that issue and merge this after I changed the double border for the label in nautilus

**Comment by Feichtmeier** [comment]
screenshot from 2018-06-30 18-33-32

screenshot from 2018-06-30 18-34-12

@madsrh I know it did look strange in your mockup. But tried it in scss and added a border radius and a box-shadow and I must say... it looks pretty neat :dancer:  I guess you don't like it? :D

**Comment by Feichtmeier** [comment]
needed to remove the box-shadow because nautilus forgets to clear up the shadow and the shadow "hangs" in the air if you select a smaller label after a bigger label -.- /facepalm

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr581`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr581` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Okay @Feichtmeier I gave this a try and your PR fixes the problem, but I'm not convinced this is the right solution. It look a bit odd IMHO that the label is floating ☁️ 

Do we agree that the current label for the light theme in edge is fine???

image
---

If so, other options for the dark theme could be:

1. simply removing the border _(yes, I've added transparency')_
image

2. a darker label (here it is #111111 with transparency) without a border
image

**Comment by Feichtmeier** [comment]
I don't like the sharp edges. Everything has a round edge. I try the transparency but with a border radius at the edges which don't touch the window border

**Comment by madsrh** [comment]
image

**Comment by Feichtmeier** [comment]
screenshot from 2018-07-01 16-46-09
screenshot from 2018-07-01 16-45-49

**Comment by madsrh** [comment]
Look good @Feichtmeier 👍 Let's go with that, but could you make [the light one](https://user-images.githubusercontent.com/15329494/42135670-47787d4e-7d4e-11e8-8e26-121b98456f47.png) have a white/bright/gray bakcground?

**Comment by Feichtmeier** [comment]
That's the color of the sidebar:
peek 2018-07-01 16-52

Maybe with a border? Or just a bit darker than in this gif?

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr581`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr581` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
> Maybe with a border? Or just a bit darker than in this gif?

Both good solutions, because it looks a bit messy (like the popovers did) when there's icons below

**Comment by Feichtmeier** [comment]
peek 2018-07-01 16-59
That's 20% darker sidebarcolor

That's transparent white but with a border:
peek 2018-07-01 17-00

**Comment by madsrh** [comment]
Hmmm, how about not making it dark, but just less transparent? 🤔

**Comment by Feichtmeier** [comment]
As discussed in telegram we go for the one you liked but with less transp :)

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr581`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr581` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr581`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr581` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by izznogooood** [comment]
This might be the wrong place to ask, but how do you enable the Drak theme?

**Comment by Feichtmeier** [comment]
@izznogooood it's definitely a strange place!

sed -i 's/gtk-application-prefer-dark-theme=1/gtk-application-prefer-dark-theme=0/g' ~/.config/gtk-3.0/settings.ini

But this is not supported yet. We might ship a dark version in some weeks. Better wait for it

**Comment by clobrano** [comment]
@izznogooood yep not the right place :smile:
 
There is no more a switch for dark theme, we're not really supporting dark theme as well (for now).
For questions like this one look here -> https://www.ubuntu.com/support/community-support

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr581`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr581` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
@Feichtmeier Just for the record, I'm concerned that the dark tooltip style is too much (aka too eye catching) BUT as you mentioned the white labels can sometimes drown if there's a lot of text.
I think we should give the dark version a try as this one has great usability. 
Can we merge your PR❔ 

### drowning:
image



### tooltip-style:
image

**Comment by Feichtmeier** [comment]
Okay just one last question: should I remove the border? I think I have added it when we tried the light one

**Comment by madsrh** [comment]
> Okay just one last question: should I remove the border? I think I have added it when we tried the light one

I would say no border, but you can't really see it, so it doesn't matter IMO. I guess that's in the code cleanup department ;)

**Comment by Feichtmeier** [comment]
Okay I remove it this eve and merge after

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr581`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr581` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Pull request merged**
