### PR TITLE
Enhance_installation_colors_in_software

### PR DESCRIPTION
**Pull request by Feichtmeier**
Fixing this https://github.com/ubuntu/gtk-communitheme/issues/383:
peek 2018-04-29 11-22

Looks good @madsrh ?
screenshot from 2018-04-29 17-02-47

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr385`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr385` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by clobrano** [comment]
Considering that padding and margin are fixed, it's probable that with 2 digit number of updates the label will be enlarged in any case

+1 on green label if possible or our indication blue

**Comment by Feichtmeier** [comment]
Yup tested it with the inspector, it will grow!
Anyways, as I wrote in the mail, I have no idea how to color the background. Every common things I know about css do not work :| It is somewhere set and I can not overwrite it. Just tested and changed the $selected_bg_color to green ;D Guess what happens, yes everything orange went green, including this counter

**Comment by Feichtmeier** [comment]
Pfffff I can cheat it green with a box-shadow and a border.....
image

  .counter-label {
    margin-top: 2px;
    margin-bottom: 2px;
    border: 2px solid $green;
    box-shadow: inset 0 0 10px 10px $green;
  }

**Comment by Feichtmeier** [comment]
When one removes the border the squircle's sides are even:
image
Still can't find the child and thus there are these little orange pixels left because this is only the box-shadow chear

**Comment by madsrh** [comment]
@Feichtmeier yeah, that one is close. It's much improved from [the first suggestion](https://user-images.githubusercontent.com/15329494/39407977-58487f6c-4bcf-11e8-966e-3e5b1931451c.png) 👍 

> Are you sure about the green though?

Not at all 😆 But I do think the purple is a bit hard to spot. The _Update all_ button is suggested action, so it would (to me) also make sense that updates individually would be green, but isn't the counter also used in other places? (I can't think of any atm).

I guess from the colorpalette we would have orange, green, blue, gray and red to choose from. Anyway, it's just a suggestion because I think the orange looks a bit out of place.

**Comment by Feichtmeier** [comment]
@madsrh yeah indeed the update all button is a suggested action but the counter is not
Its an indicator so maybe blue?
image

**Comment by Feichtmeier** [comment]
Okay, so green - doesn't make much sense to me since you do not suggest anything :man_shrugging: but so many +1 for green convinced me!

**Comment by ya-d** [comment]
Its more a -1 against blue or purple… 😄 But there are other options. I'm not entirely convinced by green since new installs get the same counter. But I don't think its a huge deal either…

**Comment by Feichtmeier** [comment]
No no biggie! My concern was just the fat squircle in the current master. 
Here is margin bottom 3px:
image

**Comment by ya-d** [comment]
I just [noticed](https://github.com/ubuntu/gtk-communitheme/pull/385#issuecomment-385273822) the progress bar for installing apps: shouldn't that be blue?

**Comment by Feichtmeier** [comment]
You didn't read my comments :crying_cat_face:

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr385`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr385` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
>  Shouldn't they be blue like the progress bars in music application sliders?

Will you create a PR for that (or should it have a separate issue)?

**Comment by Feichtmeier** [comment]
I could do it in this one I think

**Comment by ya-d** [comment]
> You didn't read my comments 😿

Ooops… 🙈

**Comment by Feichtmeier** [comment]
@godlyranchdressing pl0x halp. Tried to change this freaking progressbutton for 2 hours no idea how. This GtkThemeTheming is freaking me out. I'll stay on shell theming after this PR. 100x easier

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr385`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr385` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr385`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr385` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
@madsrh no idea about the progress bar buttons.
They are  names GsProgressButtons but I don't manage to find their properties.
We could merge this green cheat + positioning now if you like, but it's still a  cheat.
My initial thought about their wrong size is fixed at least! xD
image

**Comment by madsrh** [comment]
Yes! we can but I don't like the word cheat in there. Perhaps @godlyranchdressing has a solution and knows about GsProgressButtons too.

**Pull request merged**
