### PR TITLE
Let dark variant use the same backdrop border color as the light one

### LINKED ISSUE #158: Inconsistent window titlebars / headerbars
The titlebars/headerbars are inconsistent between normal and dark variants. Dark variant has a light line under the buttons - is this an artifact from the general buttons in the dark variant (which also suffer from a ligher line under buttons)? Dark variant also has a 1 pix dark border around windows. This dark border is a nice addition (and should be in the lighter variant too) as it helps to distinguish the titlebars of overlapping inactive windows.
 
 Seeing as 'light' variant has dark titlebars, should they not be the same - and share the same code/css?

Dark titlebars. Here it is easier to distinguish the inactive titlebars:
titlebars-dark

Normal/light titlebars. Still possible to distinguish inactive titlebars, but not as clear. Still there is a difference between this and dark which should not be there.
titlebars-light

### PR DESCRIPTION
**Pull request by clobrano**
closes #158

### CODE REVIEW

**Comment by CDrummond** [comment]
Perhaps I have not merged correctly, but I see no change. However if I also change the preceding line to
```
$_wm_border: transparentize(black, 0.77);
```

Then it looks as it should.

**Comment by CDrummond** [comment]
Now the two variants match. Of course, this means all variants have non-sharp window borders...

**Comment by clobrano** [comment]
We put some effort in making backdrop windows visible changing backdrop colors only (so that it's clearly visible in a 13'' screen like the one I'm using now) and to me the difference is still enough. 

image

**Comment by CDrummond** [comment]
The windows look great! And so does the theme overall. I'm just nitpicking with the _slightly_ blurry windows.

**Pull request merged**
