### PR TITLE
Infobar buttons

### PR DESCRIPTION
**Pull request by godlyranchdressing**
Also use blue instead of purple for some prompts:

screenshot from 2018-04-30 11-45-10
screenshot from 2018-04-30 11-44-51

trash

trash2

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Let @madsrh double check uppon this so we don't have to revert anything if it's wrong =D

**Comment by madsrh** [comment]
@godlyranchdressing Isn't the disabled button taking a lot of focus? How about making it a bit more discreet?

image

**Comment by Feichtmeier** [comment]
Me too. I think the purple was not bad. But the yellow is ofc unthemed

**Comment by madsrh** [comment]
@Feichtmeier Yellow looks a bit odd here, but you it's so normal [for info bars](https://github.com/ubuntudesign/vanilla-design/blob/master/Notifications/notifications.png).
Adwaita has no background at all. What about something like this or is it too gray, dull and sad?

image

**Comment by Feichtmeier** [comment]
:crying_cat_face: please let's not go the grey road again
Maybe I wrote this a bit strange: what I meant was -> yellow is ofc the wrong color -> let's replace it with purple and have all info bars purple. Purple is not used at all otherwise. Despite the log in screen. Blue is used for progress-bars and sliders. But I am bad at this, I don't want to decide this - you are the designer!!111 ;D

**Comment by clobrano** [comment]
Sorry for the silly question, but are the borders and shadows black/grey? If so, I think they might be more soft if using a dark blue/purple/yellow

**Comment by godlyranchdressing** [comment]
@madsrh that gray looks sad (which might be appropriate for files about to be deleted, but still). Some notes for possible color options:

The infobar for Nautilus' trash bin is `infobar`, which I think doesn't use any color at all in Adwaita. Plain infobars using a color is new to the communitheme. Right now `infobar`, `infobar.info` and `infobar.question` use purple while `infobar.warning` and `infobar.error` use yellow and red respectively. 

Part of the reason why I like the purple is _because_ it isn't used anywhere else in the theme but is still an "Ubuntu color" so it also isn't totally removed.

@clobrano they are a dark blue/purple/gray. :laughing: I used the regular button mixin so the colors just happen to be calculated like that. Should we allow colored buttons to have lighter border colors? I do think that destructive buttons go a bit too dark. I'll post some mockups later today.

**Comment by madsrh** [comment]
@godlyranchdressing I'm **perfectly fine** with the purple 👍  I've tried a lot of options and of all of them, purple is a good choice.

I still think the disabled buttons should be less intrusive (see above) 😉

**Comment by godlyranchdressing** [comment]
Lighter border-bottom and border-top colors:
zpeek 2018-05-02 14-19
wpeek 2018-05-02 14-18
peek 2018-05-02 14-18

**Comment by ya-d** [comment]
**1. Suggested action buttons:** Could the same changes be applied to suggested action buttons too? They are still flat which (in combination with rather low contrast for the text) makes them somewhat look disabled to me. I think the effect is now subtle enough to also have it on header bar. Or would that be in conflict with design decisions (flat buttons in header bar)?

_// Thinking one step further: Could/Should even the hover effect for regular header bar buttons have the same 3-dimensional look?_

orange text selection - save dialogue

**2. GDM buttons:** This is probably the wrong place but I didn't know where else to report it. GDM buttons could use the same treatment.
gdm buttons

**Comment by Feichtmeier** [comment]
And please not more 3d. The flat hover fits very well.

**Comment by Feichtmeier** [comment]
Isn't this PR finished? Even is @godlyranchdressing is a little afk atm this seems ready to merge for me? @clobrano @madsrh ?

**Comment by clobrano** [comment]
**ads2000** [comment](Ubuntu Community Hub
https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1083) on the HUB made me think a little. Since the usage of any color seems a bit forcing (if I get it right), why not use colors already present in Nautilus? Like the color behind tabs or the one in header when using list view?

**Comment by Feichtmeier** [comment]
Like adapt them to the app notification colors (white/porcelain)?

**Comment by clobrano** [comment]
We use white also for "search", so it might be a solution, even if it is a widget inside the active view, while infobar is outside

image


 otherwise the sidebar color which we use for inactive tabs as well

image

**Comment by Feichtmeier** [comment]
38277809-bbc73212-3767-11e8-878c-25370292e48c
Here for reference.
We could use a box-shadow too

**Comment by clobrano** [comment]
Something like this. Just an idea though, re-reading the thread, I saw that the agreement on purple was reached.

image

**Comment by Feichtmeier** [comment]
I am a bit torn.
On the one hand purple could be good choice because this is something between a notification (white) and and activiy (blue) so the unused purple could make sense.
On the other hand there is not much difference between these info bars and shell/-appnotification with buttons and a dialog so white would be the most obvious choice.
If we stick with the current color scheme, blue feels wrong though. It is no progress and no real activity.

**Comment by clobrano** [comment]
In Nautilus I see this infobar not different than tabs or search bar, it is just a "toolbar" let's say. However, infobar are used elsewhere, only I don't remember where, and in other application white might be the wrong color, then sorry for the noise :)

**Comment by chrisjbillington** [comment]
> On the other hand there is not much difference between these info bars and shell/-appnotification with buttons and a dialog so white would be the most obvious choice. But white is quiet hard to see.

...well minds keep changing about whether notifications and shell dialogs should be white or dark...what if they were purple? Then the info bars could be purple *and* be the same colour as the shell notifications. Don't know whether purple in shell dialogs would look completely ridiculous, but I'm quite fond of the purple info bars.

**Comment by Feichtmeier** [comment]
@chrisjbillington the white notifications will stay as far as I understoog @madsrh  and @luxamman they like them. Purple shell notifications would look very strange and alien to me.

I just found out while trying the dark theme a bit more that these infobars are quiet often used in PitVi:
image

**Comment by clobrano** [comment]
So, since info, warning and error have all color well defined, I'll give blue, yellow and red a chance

**Comment by Feichtmeier** [comment]
@clobrano tbh you are right. Purple just does not make much sense now after we've gone very heavy in the unity8 direction other than in the GDM screen. Sorry for changing my mind so easily (when good arguments pop up why not=) ? )

ecf799316df0f1c3eb7c3c13a3d772a3290cec89

**Comment by godlyranchdressing** [comment]
So we're moving from the purple to the blue?

**Comment by Feichtmeier** [comment]
Imho it would make the most sense from the arguments we've seen in here. I also like the purple but it does not really fit the current color palette we've taken from unity 8

**Comment by madsrh** [comment]
> So we're moving from the purple to the blue?

If so, does anyone have another suggestion than [this one](https://github.com/ubuntu/gtk-communitheme/pull/389#issuecomment-385507266)? I know it makes sense, but this isn't really pretty IMO.

🤔

**Comment by Feichtmeier** [comment]
It's also used in pitivi:
https://github.com/ubuntu/gtk-communitheme/pull/444

**Comment by clobrano** [comment]
> So we're moving from the purple to the blue?

Just an idea. I think however that if we don't find an agreement, better keep things as they are or we end up as with buttons :smile: 

> If so, does anyone have another suggestion than this one? I know it makes sense, but this isn't really pretty IMO.

What about [this](https://github.com/ubuntu/gtk-communitheme/pull/389#issuecomment-388790955)

**Comment by ya-d** [comment]
Nothing really is wrong with purple, most of you seem to like it and no one complained afaik. As long as there is no clear agreement and coherent reasoning I wouldn't rush changes.* Purple is used for gdm and terminal so it's not alien to the theme. It's also Ubuntu's well known secondary colour.* Blue is actually in the palette but it's currently used exclusivly for activity which doesn't match this use case. It's also very cold and doesn't fit the design language very good.* White/grey could be an option but it's very natural so it might not be a good fit for info bar. Might lead to issues for some apps where info bars should be visible more prominently.Logic didn't pave a way so far imho, which is why I would stick with taste for the time being - and I subjectivly like the use of purple. 😊Am 21.05.2018 09:36 schrieb Carlo Lobrano <notifications@github.com>:
So we're moving from the purple to the blue?

Just an idea. I think however that if we don't find an agreement, better keep things as they are or we end up as with buttons 😄

If so, does anyone have another suggestion than this one? I know it makes sense, but this isn't really pretty IMO.

What about this

**Comment by godlyranchdressing** [comment]
@clobrano 
> Just an idea. I think however that if we don't find an agreement, better keep things as they are or we end up as with buttons smile

I agree, looks like we're all on the same page at least for now.

I forgot that since I reversed the color change, all this PR does is give the infobar buttons a much needed finetuning so I'll just go ahead and merge this.

**Comment by madsrh** [comment]
The buttons are currently really hard to spot because the blend too much with the background.
image

## I would suggest one of these:

A lighter background (something midway between the purple background and the hover color)
image

Or simply use regular buttons
image

**Comment by clobrano** [comment]
Maybe the second one is simpler to work on when in hover? The first has already a quite bright purple in normal state

**Comment by madsrh** [comment]
> Maybe the second one is simpler to work on when in hover? The first has already a quite bright purple in normal state.

**+1** Using a standard button would also help keep it simple 👍 

BTW, The purple color works nicely here 🎨

**Comment by Feichtmeier** [comment]
That normal button is a great idea. Draws the whole look a bit back from "alien"

**Pull request merged**
