### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by godlyranchdressing**
Button overhaul
Scrap transparency and darken headerbar (trial period?)
Use blue for progressbars and sliders

### CODE REVIEW

**Comment by galgalesh** [comment]
LGTM :100:

**Comment by galgalesh** [comment]
@godlyranchdressing your PR has merge conflicts. I don't feel confident fixing them myself, can you fix them?

It looks good to me otherwise..

**Comment by galgalesh** [comment]
PS: where did you find these terminal colors? They seem good at first sight, I'll test them out for the next few days.

**Comment by godlyranchdressing** [comment]
@galgalesh I got them from [Unity 8](https://design.canonical.com/wp-content/uploads/04c4/terminal-blog-desktop-detail.jpg), and great, I was hoping you'd be able to give feedback. 

I have no attachment to the new teal colors in case we have to go back to the purple.

**Pull request merged**
