### PR TITLE
Fixed gedit and menu issues

### PR DESCRIPTION
**Pull request by vinceliuice**
1. Fixed gedit Document panel row close button color issues
2. Removed gedit-search-entry-occurrences-tag ugly border
3. Removed firefox rounded menu corners
4. Removed menu overflow arrow button extra space

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Hi Vince great! Thank you for this PR! Did you check if non CSD gtk3 menus are also affected like for example in gnome terminal? That was my problem when trying that :(

**Comment by Feichtmeier** [comment]
@vinceliuice any chance you could also fix the border radius of the sub menu?
submenu

It should look like this for gtk3 not CSD menus from menu bars:
- top edges no border radius <-----
- bottom edges small radius  <----- we have this at the moment :+1: 
- submenu small radius for top and bottom  edges <--- that's missing

**Comment by clobrano** [comment]
Is it possible to close the selection ring? In the last picture the right border is missing

**Comment by vinceliuice** [comment]
@clobrano I know how to fix this, I'll pull a PR later for this

**Comment by vinceliuice** [comment]
image

**Comment by vinceliuice** [comment]
@Feichtmeier Now submenu top border radius have added back ( Sorry about the wrong title of second commits, It should be add not removed ) you can try this

**Comment by Feichtmeier** [comment]
Hi Vince no you misunderstood me. Sorry for removing that comment but I thought it would be too much for this pr after writing it. What would be the best would be to have the submenus and csd menus have all 4 edges round and the not CSD menus have them round only on bottom. If that's not possible rather keep them as they are

**Pull request merged**
