### PR TITLE
Made suggested action label button more visible when disabled

### LINKED ISSUE #235: Suggested Action Button could use a different contrast when deactivated
screenshot from 2018-03-07 17-51-31
screenshot from 2018-03-07 17-50-12

It is really hard to read and looks a bit out of place. Nothing really bad but could be an improvement to change the green when it is deactivated to something lighter, so you can read the text.
I try to find an example in the bright version of this theme meanwhile, though the suggested action color is green anyways

### PR DESCRIPTION
**Pull request by clobrano**
closes #235 
Before
image

After
image

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr526`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr526` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
image
image

**Comment by clobrano** [comment]
Yes, I can increase just a little the transparency, but at the moment I cannot test on Geary (google does not let me to use this _insecure_ app :D)

alpha 0.45 -> 0.55
image

0.6
image

0.65
image

**Comment by Feichtmeier** [comment]
Yeah you need to toggle "allow insecure apps" in your Google account. However, sorry for merging this too early. I would also tweak the alpha rather than the silk text colour you introduced

**Comment by madsrh** [comment]
> ...However, sorry for merging this too early.

Don't be sorry - it's your birthday!!! :gift: :balloon: :cake: :cocktail: :beer: :de: 

@clobrano The merged one is almost good, so you pick one above. My issue was more with the light version @Feichtmeier posted screenshots of.

**Comment by clobrano** [comment]
Yeah, I enabled insecure app, but still didn't work, maybe it requires a little time, I'll try again later

**Pull request merged**
