### PR TITLE
Mockup/new breadcrumbs style

### LINKED ISSUE #94: Apply new breadcrumb style from mockup
image

design from [here](https://community.ubuntu.com/t/mockups-new-design-discussions/1898/174)

### PR DESCRIPTION
**Pull request by clobrano**
closes #94 

actual result
new-pathbar01

### CODE REVIEW

**Comment by galgalesh** [comment]
The enabled arrows next to the path bar still look disabled. In this screenshot, from left to right the arrows are

enabled - disabled - enabled - <path> - disabled

image

I think the pathbar arrows and font should follow the same color scheme as the arrow buttons on the left; that would make it more clear which ones are enabled and which ones aren't.

**Comment by didrocks** [comment]
> I think the pathbar arrows and font should follow the same color scheme as the arrow buttons on the left; that would make it more clear which ones are enabled and which ones aren't.

+1

**Comment by clobrano** [comment]
> I think the pathbar arrows and font should follow the same color scheme as the arrow buttons on the left; that would make it more clear which ones are enabled and which ones aren't.

Consider that the arrow on the leftmost has a different behavior: disable/enable -> dark/light, hover -> background gets gray.
leftmostarrow


The arrows at the borders of pathbar, instead, do not have any background highlight for consistency with the rest of the pathbar. This means we need three level of highlight: disable:dark, enabled:light, enabled+hover:lighter
pathbararrow



That said, I am not too happy with current solution, too, but I'm already using $silk (#CCC) for enabled color and white for enabled+hover and it looks too dark as well.

**Comment by galgalesh** [comment]
Hmm, this is a tough one :confused: 

The flat headerbars are really difficult to get right, it seems..

I'll merge this so the others can give feedback on it.

**Pull request merged**
