### PR TITLE
Made overlay-indicator (scrollbar) transparent and borderless

### LINKED ISSUE #395: Background color of scrollbar looks weird
I think background color of the scrollbar should be white? In this case it looks pretty weird.

### PR DESCRIPTION
**Pull request by clobrano**
closes #395

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr405`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr405` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by Feichtmeier** [comment]
tried the pull :+1: solves the problem and uses good in general 
peek 2018-05-06 16-42

**Comment by madsrh** [comment]
Looks good, but could the scrollable area have a semi transparent background?

image

> solves the problem...

Yes, but it still gives the impression that you're not at the top, so we still want #109 also.

**Comment by clobrano** [comment]
slider-semitransparent

**Pull request merged**
