### PR TITLE
Pale blue as selected color for editable text only

### LINKED ISSUE #307: Change color for selected text
The selected text color is current orange. When selecting a lot of text, the current orange is really overwhelming. Lowering the opacity never looks good with orange, so [this light blue from Unity8](https://mir-s3-cdn-cf.behance.net/project_modules/1400/79cff89167887.58df91ab0e4e7.jpg) might be a good solution. I can't find it in the documentation, but here it looks like **#d2effd**

image

TODO
- [ ]  Adapt LibreOffice text selection to madsblue -> actually open a ticket on Libreoffice about this
- [x] Adapt Firefox text selection to madsblue (in progress)

### PR DESCRIPTION
**Pull request by clobrano**
closes #307

### CODE REVIEW

**Comment by clobrano** [comment]
Ah, yes sorry

**Comment by Feichtmeier** [comment]
image

image

image

screenshot from 2018-05-29 22-53-38
image


Works everywhere as suggested :+1: 

Only evince PDF viewer is missing

**Comment by clobrano** [comment]
> Only evince PDF viewer is missing

but pdf viewer is not editable text :thinking:

**Comment by Feichtmeier** [comment]
I saw no one else voting strictly against my comment from:
https://github.com/ubuntu/gtk-communitheme/issues/307#issuecomment-387080772
After that comment everyone just talked about which color :D

**Comment by clobrano** [comment]
Sorry, I took for granted the simpler rule "editable text" :)

**Comment by Feichtmeier** [comment]
Nothing to be sorry about its very confusing and I just double posted this on both the issue and this PR because I am already confused ;D

**Pull request merged**
