### PR TITLE
selectedtext_in_entries_orange

### PR DESCRIPTION
**Pull request by Feichtmeier**
As discussed here: https://github.com/ubuntu/gtk-communitheme/issues/307#issuecomment-394825278

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/gtk-communitheme-pr517`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/gtk-communitheme-pr517` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by madsrh** [comment]
Anyone (_besides me)_ in favor of merging this one? 😄  @Feichtmeier @clobrano ?

**Comment by clobrano** [comment]
Sorry, I'd rather have everything orange (even lighter one) that some blue here and some orange there :(

**Comment by madsrh** [comment]
This PR would be an improvement to the current we have in edge - I really don't like the orange+blue mix in entryfields.

 > Sorry, I'd rather have everything orange (even lighter one) that some blue here and some orange there :(

Don't be sorry 😁 It has been a journey, but I'm +1 for full orange like we started with.

**Comment by Feichtmeier** [comment]
🍊 everywhere yes but transparency please

**Comment by Feichtmeier** [comment]
So close the two text selection pr and we discuss it on the other PR?

**Comment by madsrh** [comment]
Please keep solid orange for entryfields 🙏

**Comment by clobrano** [comment]
Let's try to recap:

- [x] solid orange on entry fields
- [ ] transparent orange on text selection (editable or not)?

**Comment by madsrh** [comment]
We don't have time for another round around the color palette before October 😆 let's give 🐟 a try!

**Pull request closed without merging**
