### PR TITLE
Nemo tweaks

### LINKED ISSUE #599: Minor tweaks for Nemo
## Minor tweaks for Nemo

* Make icons less shiny in backdrop [like Nautilus](https://github.com/ubuntu/gtk-communitheme/pull/442). I don't know the name of the container, but something like this:

`.view:backdrop { opacity: 0.9; }`

* On selection, only the label should be colored. Not sure if [this ](https://github.com/ubuntu/gtk-communitheme/pull/48) is the PR from Nautilus 🤷‍♂️ Oddly enough, list view is fine - only icon view and compact view are affected.

image

* Add padding to the **Close** button in preferences:

`.dialog-action-area { padding: 2 6 4; }`

image

* No one will ever see this one, so don't spend any time on it, but in backdrop the primary-toolbar background in preferences doesn't change to "backdrop gray"

image

### PR DESCRIPTION
**Pull request by godlyranchdressing**
Closes #599
Also links the linked buttons in the toolbar.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Aaron is back in town /cheer

**Comment by madsrh** [comment]
> Mads check it please I can't atm

I can't check without the didrocks robot 🤖 🤷‍♂️  Sorry for being a technical imbecile 😢

**Comment by godlyranchdressing** [comment]
One thing I note is that the stackswitcher doesn't look as it should with the underline effect, it looks more like linked buttons. Should I fix it or leave it as is?

**Comment by Feichtmeier** [comment]
Hmmm ... I don't want to install nemo on my production machine (where I code for communitheme)
Would have been great if you would have make the PR from a repo clone for the automatic snap
Anyways, I am pretty sure that you've tested it yourself and since nemo is not very crucial could you just upload some screenshots about the fixes and we merge it

**Comment by Feichtmeier** [comment]
> One thing I note is that the stackswitcher doesn't look as it should with the underline effect, it looks more like linked buttons. Should I fix it or leave it as is?

I can't check this at the moment as I don't want to pollute my precious gnome with nemo :dancer: 
And you didn't provide a snap because you made the PR from your fork repo :D 

So without screenshots we have no idea what happened.
If you have one more thing to fix for nemo you can surely do this in this PR! =)
No hurry for nemo needed imho

**Comment by clobrano** [comment]
I'll check it :+1:

**Comment by clobrano** [comment]
Everything looks good, except this weird effect (not introduced by this PR), but I don't want to stop this, so I'll open a new bug

peek 2018-07-07 17-41

**Pull request merged**
