### PR TITLE
Fixed spinbutton hover color in dark variant

### LINKED ISSUE #498: Spinbutton dark variant hover effect is too bright
previously reported [here](https://github.com/ubuntu/gtk-communitheme/pull/469#issuecomment-391134919)

image

### PR DESCRIPTION
**Pull request by clobrano**
closes #498

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Works but something happend to the spin btns there is some strange shadow in them:
yayacdscsd
What happened to the dark theme? :O

**Comment by clobrano** [comment]
Do you mean the box-shadow on top? It is there in the light theme as well, it doesn't look bad to me

**Comment by Feichtmeier** [comment]
Yes, previously they looked like they were a half or a quarter level above the surface. Now with the shadow it looks like they are a quarter pressed into the surface

**Comment by clobrano** [comment]
Actually, since nothing actually changed and since this PR is for hover effect, I'd better merge this and open a specific issue for the other problem

**Pull request merged**
