### PR TITLE
Use $fg_color for entry fields, inactive tabs use $text_color

### PR DESCRIPTION
**Pull request by godlyranchdressing**
Closes issue #156 
Closes issue #157

### CODE REVIEW

**Comment by nana-4** [comment]
I feel we should use `$inkstone` for `$text_color` instead of using `$fg_color` for entry fields. (Although I personally prefer more darker color than `$inkstone` for text colors.)


The original #157 reporter also refers to the low contrast of **views** and **menus**, and I agree with that. But only changing entry fields will not solve other contrast lowness.

**Comment by godlyranchdressing** [comment]
@nana-4 `$fg_color` uses `$inkstone` already. Maybe `$inkstone` for `$text_color` and `$jet` for `$fg_color`?

screenshot from 2018-02-15 11-27-23

I think `$jet` is a little too dark though. I'd like to stick to the color palette that's available but maybe we should try using another color. This is `$inkstone (#3D3D3D)` for `$text_color` and `#2D2D2D` for `$fg_color`:



We also have cool grey (#333) and text grey (#111) from the [Ubuntu palette](https://design.ubuntu.com/brand/colour-palette/) to work with.

**Comment by nana-4** [comment]
@godlyranchdressing I mean, I suggested using `$inkstone` for both `$fg_color` and `$text_color`. :)

Yeah, I agree `$jet` is a little too dark. Personally, a slightly darker color than `$inkstone` (like `#333333`) is just right to me. But I also agree to stick to the color palette that's available.

IMHO it would be good to update the color palette and make `$inkstone` a little darker, but it may be necessary for more discussion among designers about which color (or brightness) is most suitable for text colors.

**Comment by clobrano** [comment]
Sorry, what's the state of this PR? Can be merged?

**Comment by godlyranchdressing** [comment]
@clobrano I guess. I'm just wondering if to darken $fg_color and $text_color or stick to the palette. I like #3D3D3D and #2D2D2D seen [here](https://user-images.githubusercontent.com/27529229/36264892-58a33a48-1244-11e8-9c83-0d712bcb0850.png) but I wonder if the difference between the two shades is too little, or if we even need a distinction between "text" and "fg". 

It did _come with Adwaita_ but is that enough reason to keep both around? I'm on board with just using $inkstone for both $fg_color and $text_color.

@Luxamann and @madsrh , what do you guys think?

**Comment by clobrano** [comment]
They look different enough to me
image

> It did come with Adwaita but is that enough reason to keep both around? I'm on board with just using $inkstone for both $fg_color and $text_color.

It's ok to me to keep just one color, but to make it easier to manage future rebase on Adwaita project, I would keep the names in common.scss and assign them the same value on our color.scss

What do you think guys?

**Comment by nana-4** [comment]
> It did come with Adwaita but is that enough reason to keep both around?

FYI, Adwaita didn't have `$text_color` until several years ago.
See https://bugzilla.gnome.org/show_bug.cgi?id=726316 for details.

**Comment by madsrh** [comment]
After [discussing font-weight](https://github.com/Ubuntu/gtk-communitheme/issues/181) with @nana-4 yesterday, I did [a bunch of tests](https://www.dropbox.com/s/g97f1zs7leg5c3z/fontcolors.gif) and I agree that if there's a color we can use that sits between Jet and Inkstone it would be perfect. #2d2d2d seems to fit here.

**Comment by clobrano** [comment]
Ok, so I'd wait @godlyranchdressing for the last fixes (if he wants to) and then we can merge this

**Comment by godlyranchdressing** [comment]
Sorry, I'm a little behind. So we're agreeing to change $fg_color and $text_color. What values are we using for each?

**Comment by clobrano** [comment]
> I'm just wondering if to darken $fg_color and $text_color or stick to the palette. I like #3D3D3D and #2D2D2D seen here but I wonder if the difference between the two shades is too little, or if we even need a distinction between "text" and "fg".

wasn't this one the only doubt remained?
If I got it right, @madsrh is OK with #2D2D2D

**Comment by madsrh** [comment]
Yes, this is perfect, but I would like to suggest another color change. Should I merge this and start another issue? I'm guessing it's a quick fix.

Change disabled hover color for text in lists to **#ee886e** as the current (the one in the bottom) is very hard to read.

See the comparison here:
colors_

**Pull request merged**
